version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "6060:6060"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
