version: '3.8'
services:
 app:
   build: .
   volumes:
     - .:/app
   ports:
     - "6060:6060"
   depends_on:
     - db
   environment:
     - DATABASE_URL=mysql://root:password@db:3306/shift_scheduler
 db:
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: shift_scheduler
   ports:
     - "3306:3306"