"""your_message

Revision ID: 0247376a6cb3
Revises: dd959c67adc1
Create Date: 2025-05-09 08:44:56.836146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0247376a6cb3'
down_revision: Union[str, None] = 'dd959c67adc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_results', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.add_column('shift_results', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shift_results_id'), 'shift_results', ['id'], unique=False)
    op.create_foreign_key(None, 'shift_results', 'shifts', ['shift_id'], ['id'])
    op.create_foreign_key(None, 'shift_results', 'staffs', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_results', type_='foreignkey')
    op.drop_constraint(None, 'shift_results', type_='foreignkey')
    op.drop_index(op.f('ix_shift_results_id'), table_name='shift_results')
    op.drop_column('shift_results', 'shift_id')
    op.drop_column('shift_results', 'staff_id')
    # ### end Alembic commands ###
