"""Add year and month columns to Shift model

Revision ID: 0c43973a8d3f
Revises: 972bb2b734ae
Create Date: 2025-05-28 01:03:09.461531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c43973a8d3f'
down_revision: Union[str, None] = '972bb2b734ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('shifts', sa.Column('month', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'month')
    op.drop_column('shifts', 'year')
    # ### end Alembic commands ###
