"""Make shift_patterns

Revision ID: 257cecc6af6d
Revises: 03aa3821b07e
Create Date: 2025-05-12 03:26:54.948942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '257cecc6af6d'
down_revision: Union[str, None] = '03aa3821b07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('is_fulltime', sa.Boolean(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('store_default_skill_requirements', sa.Column('peak_people', sa.Integer(), nullable=False))
    op.add_column('store_default_skill_requirements', sa.Column('open_people', sa.Integer(), nullable=False))
    op.add_column('store_default_skill_requirements', sa.Column('close_people', sa.Integer(), nullable=False))
    op.drop_column('store_default_skill_requirements', 'people')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_default_skill_requirements', sa.Column('people', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('store_default_skill_requirements', 'close_people')
    op.drop_column('store_default_skill_requirements', 'open_people')
    op.drop_column('store_default_skill_requirements', 'peak_people')
    op.drop_table('shift_patterns')
    # ### end Alembic commands ###
