"""initial migration

Revision ID: 40b0454e3e90
Revises: 
Create Date: 2025-05-07 09:10:42.072937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b0454e3e90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_default_skill_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('kitchen_a', sa.Integer(), nullable=False),
    sa.Column('kitchen_b', sa.Integer(), nullable=False),
    sa.Column('drink', sa.Integer(), nullable=False),
    sa.Column('hall', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_skill_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('kitchen_a', sa.Integer(), nullable=False),
    sa.Column('kitchen_b', sa.Integer(), nullable=False),
    sa.Column('drink', sa.Integer(), nullable=False),
    sa.Column('hall', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_results_id'), 'shift_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_results_id'), table_name='shift_results')
    op.drop_table('shift_results')
    op.drop_table('store_skill_overrides')
    op.drop_table('store_default_skill_requirements')
    # ### end Alembic commands ###
