"""add date field to Shiftresult

Revision ID: 41fba14dba76
Revises: 257cecc6af6d
Create Date: 2025-05-13 03:52:40.861256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41fba14dba76'
down_revision: Union[str, None] = '257cecc6af6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_results', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('shift_results', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('shift_results', sa.Column('day', sa.Integer(), nullable=False))
    op.drop_column('shift_results', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_results', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('shift_results', 'day')
    op.drop_column('shift_results', 'month')
    op.drop_column('shift_results', 'year')
    # ### end Alembic commands ###
