"""Make

Revision ID: 474acfde3121
Revises: 6fb45ac6364a
Create Date: 2025-05-02 08:45:24.889191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474acfde3121'
down_revision: Union[str, None] = '6fb45ac6364a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_requests', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shift_requests', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_requests', type_='foreignkey')
    op.drop_column('shift_requests', 'store_id')
    # ### end Alembic commands ###
