"""initial migration

Revision ID: 54b6a5deaa4b
Revises: 
Create Date: 2025-05-03 14:37:40.942301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b6a5deaa4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('open_hours', sa.Time(), nullable=False),
    sa.Column('close_hours', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('男', '女', name='gender_enum'), nullable=True),
    sa.Column('desired_days', sa.Integer(), nullable=False),
    sa.Column('kitchen_a', sa.Integer(), nullable=False),
    sa.Column('kitchen_b', sa.Integer(), nullable=False),
    sa.Column('drink', sa.Integer(), nullable=False),
    sa.Column('hall', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.Enum('社員', 'バイト', '未成年バイト', name='employment_type_enum'), nullable=False),
    sa.Column('login_code', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('drink BETWEEN 0 AND 5', name='check_drink'),
    sa.CheckConstraint('hall BETWEEN 0 AND 5', name='check_hall'),
    sa.CheckConstraint('kitchen_a BETWEEN 0 AND 5', name='check_kitchen_a'),
    sa.CheckConstraint('kitchen_b BETWEEN 0 AND 5', name='check_kitchen_b'),
    sa.CheckConstraint('leadership BETWEEN 0 AND 5', name='check_leadership'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_code')
    )
    op.create_table('shift_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('×', '○', 'time', name='status_enum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_table('shift_requests')
    op.drop_table('staffs')
    op.drop_table('stores')
    # ### end Alembic commands ###
