"""Make

Revision ID: 6fb45ac6364a
Revises: c60d2096abd3
Create Date: 2025-05-02 08:42:41.594182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fb45ac6364a'
down_revision: Union[str, None] = 'c60d2096abd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_requests', 'start_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('shift_requests', 'end_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('stores', 'open_hours',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('stores', 'close_hours',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'close_hours',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('stores', 'open_hours',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('shift_requests', 'end_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('shift_requests', 'start_time',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
