"""initial migration

Revision ID: 9a7c90e73b7d
Revises: bf637652e356
Create Date: 2025-05-09 09:40:45.675143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a7c90e73b7d'
down_revision: Union[str, None] = 'bf637652e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_requests', 'start_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('shift_requests', 'end_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_requests', 'end_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('shift_requests', 'start_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
