"""initial migration

Revision ID: c60d2096abd3
Revises: 
Create Date: 2025-05-02 04:18:09.603546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c60d2096abd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staffs', 'gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.Enum('男', '女', name='gender_enum'),
               nullable=True)
    op.alter_column('staffs', 'kitchen_a',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('staffs', 'kitchen_b',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('staffs', 'drink',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('staffs', 'hall',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('staffs', 'leadership',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('staffs', 'employment_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('社員', 'バイト', '未成年バイト', name='employment_type_enum'),
               existing_nullable=False)
    op.alter_column('staffs', 'login_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('staffs', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'staffs', ['login_code'])
    op.add_column('stores', sa.Column('open_hours', sa.String(length=255), nullable=False))
    op.add_column('stores', sa.Column('close_hours', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'close_hours')
    op.drop_column('stores', 'open_hours')
    op.drop_constraint(None, 'staffs', type_='unique')
    op.alter_column('staffs', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('staffs', 'login_code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('staffs', 'employment_type',
               existing_type=sa.Enum('社員', 'バイト', '未成年バイト', name='employment_type_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.alter_column('staffs', 'leadership',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('staffs', 'hall',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('staffs', 'drink',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('staffs', 'kitchen_b',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('staffs', 'kitchen_a',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('staffs', 'gender',
               existing_type=sa.Enum('男', '女', name='gender_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               nullable=True)
    op.create_table('staff_store',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name='staff_store_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='staff_store_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
