"""initial migration

Revision ID: dd959c67adc1
Revises: 40b0454e3e90
Create Date: 2025-05-09 07:40:49.946768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd959c67adc1'
down_revision: Union[str, None] = '40b0454e3e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_skill_overrides')
    op.alter_column('shift_requests', 'start_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shift_requests', 'end_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shift_results', 'date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shift_results', 'start_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shift_results', 'end_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shifts', 'date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('staffs', 'kitchen_a',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('A', 'B', 'C', name='kitchen_a_enum'),
               existing_nullable=False)
    op.alter_column('staffs', 'kitchen_b',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('A', 'B', 'C', name='kitchen_b_enum'),
               existing_nullable=False)
    op.drop_column('staffs', 'drink')
    op.drop_column('staffs', 'desired_days')
    op.add_column('store_default_skill_requirements', sa.Column('peak_start_hour', sa.Integer(), nullable=False))
    op.add_column('store_default_skill_requirements', sa.Column('peak_end_hour', sa.Integer(), nullable=False))
    op.add_column('store_default_skill_requirements', sa.Column('people', sa.Integer(), nullable=False))
    op.alter_column('store_default_skill_requirements', 'day_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('平日', '金曜日', '土曜日', '日曜日', name='day_type_enum'),
               existing_nullable=False)
    op.alter_column('store_default_skill_requirements', 'kitchen_a',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('A', 'B', 'C', name='kitchen_a_enum'),
               existing_nullable=False)
    op.alter_column('store_default_skill_requirements', 'kitchen_b',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('A', 'B', 'C', name='kitchen_b_enum'),
               existing_nullable=False)
    op.drop_column('store_default_skill_requirements', 'drink')
    op.drop_column('store_default_skill_requirements', 'hour')
    op.alter_column('stores', 'open_hours',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('stores', 'close_hours',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'close_hours',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('stores', 'open_hours',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.add_column('store_default_skill_requirements', sa.Column('hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('store_default_skill_requirements', sa.Column('drink', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('store_default_skill_requirements', 'kitchen_b',
               existing_type=sa.Enum('A', 'B', 'C', name='kitchen_b_enum'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('store_default_skill_requirements', 'kitchen_a',
               existing_type=sa.Enum('A', 'B', 'C', name='kitchen_a_enum'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('store_default_skill_requirements', 'day_type',
               existing_type=sa.Enum('平日', '金曜日', '土曜日', '日曜日', name='day_type_enum'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_column('store_default_skill_requirements', 'people')
    op.drop_column('store_default_skill_requirements', 'peak_end_hour')
    op.drop_column('store_default_skill_requirements', 'peak_start_hour')
    op.add_column('staffs', sa.Column('desired_days', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('staffs', sa.Column('drink', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('staffs', 'kitchen_b',
               existing_type=sa.Enum('A', 'B', 'C', name='kitchen_b_enum'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('staffs', 'kitchen_a',
               existing_type=sa.Enum('A', 'B', 'C', name='kitchen_a_enum'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.alter_column('shifts', 'start_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.alter_column('shifts', 'date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('shift_results', 'end_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.alter_column('shift_results', 'start_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.alter_column('shift_results', 'date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('shift_requests', 'end_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.alter_column('shift_requests', 'start_time',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               nullable=True)
    op.create_table('store_skill_overrides',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kitchen_a', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kitchen_b', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('drink', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hall', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('leadership', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='store_skill_overrides_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
